config/routes.rb
Arepa::Application.routes.draw do

  match 'fetch_tweets' => 'dashboard#fetch_tweets'

  root to: 'dashboard#show'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible  :username,
                   :message,
                   :location,
                   :published

  def self.fetch_tweets(query)
    tweets = tweets_from_query(query)
    build_tweets(tweets)
  end

  private

  def self.build_tweets(tweets)
    tweets.collect{ |tweet| build_tweet(tweet) }
  end

  def self.build_tweet(tweet)
    create( username:  tweet.attrs[:user][:screen_name],
            message:   tweet.attrs[:text],
            location:  tweet.attrs[:user][:location],
            published: tweet.attrs[:created_at] )
  end

  def self.tweets_from_query(query)
    TwitterService.track(query)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @tweets = Tweet.all.reverse
  end

  def fetch_tweets
    Tweet.fetch_tweets('Venezuela')

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_time(input)
    input.strftime("%B %d, %Y - %l:%M %p")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.haml
.container.tweet
  %h2.lead Los últimos tuits sobre Venezuela.
  - @tweets.each do |tweet|
    %hr
    %h6= formatted_time(tweet.published)
    %h4= tweet.username
    %p=  tweet.message
    %h6= tweet.location

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Arepa
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-top
      .navbar-inner
        .container
          %a.brand Arepa
          .nav-collapse.collapse
            %ul.nav.pull-right
            = link_to "Actualizar Feed", fetch_tweets_path, class: "nav-link"
    .span8.feed
      = yield